### PR TITLE
Fixing fit_solution_id error and ListPrimitives error

### LINKED ISSUE #103: Missing task ID in GetFitSolutionResults
After merging #101 getting the following error on pipeline runs:
```
distil-auto-ml_1  | ERROR - 2019-07-18 23:30:01,777 - v-master-8d66713 - distil.server.ServerServicer - Unexpected error occured, aborting gRPC call: 'NoneType' object has no attribute 'fit_solution_id'
distil-auto-ml_1  | Traceback (most recent call last):
distil-auto-ml_1  |   File "/app/server/server.py", line 49, in _unary_stream_interceptor
distil-auto-ml_1  |     for message in func(request):
distil-auto-ml_1  |   File "/app/server/task_manager.py", line 293, in GetFitSolutionResults
distil-auto-ml_1  |     preds_path = utils.make_preds_filename(task.fit_solution_id)
distil-auto-ml_1  | AttributeError: 'NoneType' object has no attribute 'fit_solution_id'
```

The merge has been reverted given its blocking pipeline runs.

### PR DESCRIPTION
**Pull request by odin243**
Fixing an error in PR #101 where I was trying to read the fit_solution_id from the task, when the task is not always available.

Closes #103

### CODE REVIEW

**Comment by odin243** [comment]
Also fixes a runtime error in ListPrimitives call found in the new run of Simple-TA3:
```
Exception calling application: 'PrimitiveMetadata' object is not subscriptable
```
